spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kings?useUnicode=true&characterEncoding=UTF-8
    username: 123
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.coco: debug
  file: log/kings-dev.log

server:
  port: 8848
